### PR TITLE
Remove Bech32 max length validation to support other bech32 encoded entities

### LINKED ISSUE #58: Bech32.IsValid only works for bech32-encoded addresses and not other entities
Discovered while testing bech32 decoding in cscli PR https://github.com/CardanoSharp/cscli/pull/3 using extended keys and policy keys. 

**Examples** 
- addr_xsk1fzw9r482t0ekua7rcqewg3k8ju5d9run4juuehm2p24jtuzz4dg4wpeulnqhualvtx9lyy7u0h9pdjvmyhxdhzsyy49szs6y8c9zwfp0eqyrqyl290e6dr0q3fvngmsjn4aask9jjr6q34juh25hczw3euust0dw
- policy_sk1krqllaz7ypdfj5s7ak5psunflp5ta80d6fur5wscmwetmwnht4vex2kshz6vurqn366pyxwjzka0jnfpav4hzlmqefqf0dvstxuwt7ckg5gd0

Expected `Bech32.IsValid` to return `true` but is returning `false`

### PR DESCRIPTION
**Pull request by safestak-keith**
The easing of validation for Bech32.IsValid to fix #58

### CODE REVIEW

**Comment by safestak-keith** [comment]
The appveyor build fails due to the .NET 6 upgrade for the test project. Is this something you can change @nothingalike? Worth noting [.NET 5 will reach end of support in 3 days](https://devblogs.microsoft.com/dotnet/dotnet-5-end-of-support-update/)

**Comment by nothingalike** [comment]
@safestak-keith appveyor fixed

**Comment by nothingalike** [comment]
ok so this PR is just updating the Encoding to be more generic?

**Comment by safestak-keith** [comment]
> ok so this PR is just updating the Encoding to be more generic?

Yeah, there is a bit more context in #58 but Bech32.IsValid is currently returning false for valid encoded entities (e.g. extended signing keys and policy signing keys) discovered while testing the new cscli `bech32 decode` commands.

**Review by nothingalike — APPROVED** [review]
LTGM

**Pull request merged**
