### PR TITLE
Add german wordlist

### PR DESCRIPTION
**Pull request by tweakch**
Hi, 
I added a German wordlist as first commit to your awesome library. 

I don't know if the words in there meet *requirements* but I tried to peek into the other wordlists to get a sense of what words are good.

I'll start using CardanoSharp in my projects and contribute more in the future.

You might want to add CardanoSharp to the [Tools section](https://github.com/cardano-foundation/developer-portal/edit/staging/src/data/builder-tools.js) of the [Cardano Developer Portal](https://developers.cardano.org).

### CODE REVIEW

**Comment by nothingalike** [comment]
Thanks for the PR. We can definitely validate the words. We want to make sure they are correct so we stay compliant

**Comment by nothingalike** [comment]
Alright I'm very confused as to why there isnt an already established German wordlist

**Comment by nothingalike** [comment]
alright so heres my thought. since there is no official german wordlist, lets roll with your list. if an official list ever pops up, we can make it German2 or something along those lines. we would need to support both lists.

**Comment by nothingalike** [comment]
@tweakch [CardanoSharp.Wallet 0.1.1](https://www.nuget.org/packages/CardanoSharp.Wallet/) has your PR

Example Usage
```csharp
var mnemonic = _keyService.Generate(24, WordLists.German);
var entropy = _keyService.Restore(mnemonic, WordLists.German);
```

thank you for your contribution

**Comment by tweakch** [comment]
Thank you sounds good. Will try it out later. 

Could you provide me with some links and resources to study?

**Pull request merged**
