### PR TITLE
Improve Transaction building and serializing

### PR DESCRIPTION
**Pull request by tweakch**
Start resolving #21

### CODE REVIEW

**Comment by tweakch** [comment]
not my day... lol,  I'll retry later.

**Comment by nothingalike** [comment]
Ok I just skimmed the PR, so far everything is looking good. Definitely glad you created the `Metadata` type. Might take some testing to get right but definitely want to take that approach. 

The one thing I want to change is the Serializer. I don't know if having instances to hold the values is the best route. This is why I was talking about creating some Extensions instead and just treating them as pure functions. We can provide the main object to be serialized and any dependent cbor objects. 

I'll have time tonight to start this process if you want me to just run with it a bit.

**Comment by tweakch** [comment]
Agreed. I just wanted to provide a starting point. Not final or thought through by any means.

Go ahead and run with it, I'll build some Tx with cardano-cli to add tests

**Comment by tweakch** [comment]
tests fail on purpose. the last few bytes of the CBOR mismatch. [tx.cddl](CardanoSharp.Wallet.Test/dat/01/tx.cddl) != [reference.cddl](CardanoSharp.Wallet.Test/dat/01/reference.cddl)

**Comment by tweakch** [comment]
Probably the metadata -.-

**Comment by nothingalike** [comment]
> Probably the metadata -.-

you are probably right. what is your method for debugging cbor?

**Comment by nothingalike** [comment]
alright didn't get to the transaction serialization refactor. I got lost in this consolidation hole and wrote a derivation test that doesn't use the node types.

**Comment by tweakch** [comment]
> what is your method for debugging cbor?
i use <http://cbor.me> to convert from hex to cddl. i need a reference for Cardano though. havent really looked for that yet. know one?

**Comment by nothingalike** [comment]
> > what is your method for debugging cbor?
> 
> 
> 
> i use <http://cbor.me> to convert from hex to cddl. i need a reference for Cardano though. havent really looked for that yet. know one? 
> 
> 
> 
> 

Talking about the cddl references?

https://github.com/input-output-hk/cardano-ledger-specs

The table has links to each era's cddl

As for examples to specifically compare to, i create transactions using cardano-cli and deserialize using cbor.me similar to you

**Review by nothingalike — APPROVED** [review]

**Pull request merged**
