### PR TITLE
MultiSig Wallets

### PR DESCRIPTION
**Pull request by nothingalike**
Currently im using `cardano-address` cli as my control. Here are the following commands im using

```bash
cardano-address.exe recovery-phrase generate --size 15 > phrase.1.prv
cardano-address.exe recovery-phrase generate --size 15 > phrase.2.prv
# phrase1 = scale fiction sadness render fun system hunt skull awake neither quick uncle grab grid credit
# phrase2 = harsh absorb lazy resist elephant social carry roof remember picture merry enlist regret major practice

cardano-address key from-recovery-phrase Shared < phrase.1.prv > root_shared.1.xsk
cardano-address key from-recovery-phrase Shared < phrase.2.prv > root_shared.2.xsk
cardano-address key child 1854H/1815H/0H/0/0 < root_shared.1.xsk | cardano-address key public --without-chain-code > addr_shared.1.vk
cardano-address key child 1854H/1815H/0H/0/0 < root_shared.2.xsk | cardano-address key public --without-chain-code > addr_shared.2.vk
cardano-address script hash "any [$(cat addr_shared.1.vk), $(cat addr_shared.2.vk)]" > script.hash
cardano-address address payment --network-tag testnet < script.hash > script.addr
```

the above will help you follow along with the first unit test i added.

### CODE REVIEW

**Review by Daniel-SchaeferJ — COMMENTED** [review]
Good job. Really was quite simple once you had the address type.

**Review by Daniel-SchaeferJ — APPROVED** [review]

**Comment by nothingalike** [comment]
Kyle: 500 ADA

Bounty: 500 ADA
https://github.com/CardanoSharp/cardanosharp-wallet/issues/57

**Comment by nothingalike** [comment]
Kyle: addr1q80zvrtl2sf7l463e6780mu3krc2a0q8hyagekvkrzx80n9kysua3m4jaywrsv54d2yl7v333ljv7qg7tjaj8ysfyylqzc8f8z

**Comment by nothingalike** [comment]
Kyle; https://cardanoscan.io/transaction/2571e3fbb7d3f8811c951fb633ae052be8299a308f3e71764a59c2939ae2fa10

**Pull request merged**
