### PR TITLE
TransactionUnspentOutput vs UTXO

### PR DESCRIPTION
**Pull request by lilpaul**
Added both the TransactionUnspentOutput and Utxo classes for discussion around which we are going to go with.

TransactionUnspentOutput 
- is inline with CIP30 spec
- matches current style of objects (favouring byte arrays over strings)

Utxo
- little more readable
- matches closer to style from koios (strings and flattened list of assets, not grouped by policyid)

### CODE REVIEW

**Comment by nothingalike** [comment]
I want to add that the Utxo model lends itself to the CIP2 implementation.

**Comment by lilpaul** [comment]
> I want to add that the Utxo model lends itself to the CIP2 implementation.

cool... to be honest, im actually a little more in favour of the utxo class as well, but also generally am more keen on strings in lieu of byte arrays

**Comment by safestak-keith** [comment]
Excuse my newbie question since I'm not fully aware of the context, what is the new Utxo type used for?

My two lovelaces worth of opinions - I agree with having serialisation layer types under CardanoSharp.Wallet.Transactions matching CDDL definitions and using primitives like byte[]. This gives us a clear abstraction around all the types related to CBOR serialisation/deserialisation when building the tx for the cardano node. 

So with that in mind, will/should this Utxo type also reside in that same layer/namespace? 

I also (personally) prefer a consumer friendly domain layer containing types using bech32 or hexadecimal strings instead of byte[], and mappable to/from CardanoSharp.Wallet.Transactions types. This friendly layer would also contain utility methods like CalculateMinUtxoLovelace, CoinSelection, ConsolidateTokenBundle, etc.

**Comment by lilpaul** [comment]
Good input. Theyre both used to represent unspent tx outputs, just the one class (TransactionUnspentOutput) is more closely representing the cbor that I'm getting back from the wallet extensions (nami, eternl etc) and matches the CIP30 spec, and the other Utxo is closer to the CIP2 spec and what is coming back from koios and blockfrost.

I really like the idea of maybe having both and the 2 layers you're talking about, with some functions to switch between them.

**Comment by nothingalike** [comment]
@safestak-keith 
>My two lovelaces worth of opinions - I agree with having serialisation layer types under CardanoSharp.Wallet.Transactions matching CDDL definitions and using primitives like byte[]. This gives us a clear abstraction around all the types related to CBOR serialisation/deserialisation when building the tx for the cardano node.

I definitely agree with this thought. I definitely could tell it felt weird putting it there and this identifies why. 

>So with that in mind, will/should this Utxo type also reside in that same layer/namespace?

I also (personally) prefer a consumer friendly domain layer containing types using bech32 or hexadecimal strings instead of byte[], and mappable to/from CardanoSharp.Wallet.Transactions types. This friendly layer would also contain utility methods like CalculateMinUtxoLovelace, CoinSelection, ConsolidateTokenBundle, etc.

100%. I'll update CIP2 to align better with this approach.


@lilpaul 

> Just looking over the Utxo.cs and Asset.cs now, the asset class uses bytes and utxo strings, if we are going to use these two i think we should standardise between them. My current leaning is the TransactionUnspentOutput as the class for the serialization layer and the asset class changed to strings and it combined with the Utxo class are the start of the 'friendly' layer. Maybe in their own folder or namespace with convert functions.

Agreed.

I think that brings us to the question about how to organize the library. We have wallet cryptography, transaction serialization, CIP specs, domain layer, and common utilities. 

Do we want to keep all this in one library or should we discuss breaking up the library. Current size of the library is 413.53 KB according to nuget.org.

Regardless of the approach, we should probably follow certain rules about how these areas interact.

**Comment by safestak-keith** [comment]
> I think that brings us to the question about how to organize the library. We have wallet cryptography, transaction serialization, CIP specs, domain layer, and common utilities.
> 
> Do we want to keep all this in one library or should we discuss breaking up the library. Current size of the library is 413.53 KB according to nuget.org.
> 
> Regardless of the approach, we should probably follow certain rules about how these areas interact.

Definitely agree we should start thinking about organising it a little better before we start adding more features. 

Having spent time on the consumer side building payment/minting APIs, cscli and address monitoring worker services I can see lines becoming blurred between the CDDL-mapped types used in Transaction serialisation and all the other types. 

In the medium term future I can see a core `CardanoSharp.Serialization` assembly with just the CDDL-mapped types and their builders. That would in turn be referenced by `CardanoSharp.Wallet` containing wallet primitives, domain types, CIPs and higher-level cryptography. To begin we can have them in one solution separated by solution folders or a separate projects.

At the end of the day I think the goal of **CardanoSharp.Wallet** is to allow our consumers to be as productive as possible without worrying about the lower-level serialization and byte representations, but also giving them the ability to tweak some CBOR should they need to.

**Comment by lilpaul** [comment]
> Definitely agree we should start thinking about organising it a little better before we start adding more features.
> 
> Having spent time on the consumer side building payment/minting APIs, cscli and address monitoring worker services I can see lines becoming blurred between the CDDL-mapped types used in Transaction serialisation and all the other types.
> 
> In the medium term future I can see a core `CardanoSharp.Serialization` assembly with just the CDDL-mapped types and their builders. That would in turn be referenced by `CardanoSharp.Wallet` containing wallet primitives, domain types, CIPs and higher-level cryptography. To begin we can have them in one solution separated by solution folders or a separate projects.
> 
> At the end of the day I think the goal of **CardanoSharp.Wallet** is to allow our consumers to be as productive as possible without worrying about the lower-level serialization and byte representations, but also giving them the ability to tweak some CBOR should they need to.

WRT the possible rewrite/breakup... I'd like to put a request that the serialization/deserialization is kept clean from the cryptography stuff. Im sure the signing of witnesses where there is a private key and no signature yet that happens during tx serialization currently was just intended as a convenience, but for the next version I'd like to suggest that it rather throws an exception if this is the state, and the signing is done by a seperate library, presumably the cswallet.cryptography or something like that. Anything blazor related can't use cryptography due to it not being supported by wasm.

**Comment by safestak-keith** [comment]
> WRT the possible rewrite/breakup... I'd like to put a request that the serialization/deserialization is kept clean from the cryptography stuff. Im sure the signing of witnesses where there is a private key and no signature yet that happens during tx serialization currently was just intended as a convenience, but for the next version I'd like to suggest that it rather throws an exception if this is the state, and the signing is done by a seperate library, presumably the cswallet.cryptography or something like that. Anything blazor related can't use cryptography due to it not being supported by wasm.

So the last I read around cryptography support in blazor WASM was back in the .NET 5 days where they mentioned it was too much effort to migrate all of the cryptography libraries. That said, have you tested it in your blazor WASM app with the [.NET 7 Preview](https://dotnet.microsoft.com/en-us/download/dotnet/7.0)?

I'm guessing by signing in a separate library you mean move the `vKeyWitness.SKey.Sign(txBodyHash);` bit in the block below in `VKeyWitnessExtensions.cs` to a separate library which takes the TransactionBody and AuxiliaryData as params? I'm currently working on [signing transactions for cscli](https://github.com/CardanoSharp/cscli/pull/8/files#diff-36e531eeaa2f09b9e3b661e08de2fa8ec8259f1e6a3898bc1024492b12b3b4c7) and the only way to is to add signing keys to the VKeyWitnesses and running Serialize() or GetCBOR() in the Transaction or GetCBOR() for the TransactionWitnessSet. 

```
public static CBORObject GetCBOR(this VKeyWitness vKeyWitness, TransactionBody transactionBody, AuxiliaryData auxiliaryData)
{
    //only do signing if skey is present (wont be present for deserialized transactions but signature will already be there)
    if (vKeyWitness.SKey != null)
    {
        //sign body
        var txBodyHash = HashUtility.Blake2b256(transactionBody.GetCBOR(auxiliaryData).EncodeToBytes());
        vKeyWitness.Signature = vKeyWitness.SKey.Sign(txBodyHash);
    }
    //validation
    if (vKeyWitness.VKey.Key.Length != 32)
    {
        throw new ArgumentException("vKeyWitness.VKey.Key not expected length (expected 32)");
    }
    
    //fill out cbor structure for vkey witnesses
    return CBORObject.NewArray()
        .Add(vKeyWitness.VKey.Key)
        .Add(vKeyWitness.Signature);
}
```

**Comment by lilpaul** [comment]
> I'm guessing by signing in a separate library you mean move the vKeyWitness.SKey.Sign(txBodyHash); bit in the block below in VKeyWitnessExtensions.cs to a separate library

yeah... again could just be my opinion, but signing functionality that just gives you the signature or maybe the vkeywitness, or something like that, serialization that just does serialization, and maybe a combo extension that checks for skeys that need to be used to make signatures and then does serialization.

seems like we are still quite a way from a reorganisation/rewrite, maybe we should move this discussion to the discord and close this PR?

**Comment by safestak-keith** [comment]
> seems like we are still quite a way from a reorganisation/rewrite, maybe we should move this discussion to the discord and close this PR?
Yeah let's do that

**Pull request closed without merging**
