### PR TITLE
#12 Wordlist array lookup without file IO implemented

### PR DESCRIPTION
**Pull request by safestak-keith**
Explicitly declaring wordlists as static arrays so that we can save on file IO for every mnemonic operation, this will in turn allow for less resource utilization and more ops/sec in specific use-cases (e.g. API server needing to handle lots of generate or restore mnemonic operations concurrently). Running the https://github.com/CardanoSharp/cscli tests should be much speedier too!

Note: Used https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md as reference - source of German wordlist needs TBD

### CODE REVIEW

**Comment by eddex** [comment]
While this approach certainly works, I don't like it that much for the following reasons:

1. If there is a new word list in the future, someone needs to create a new class for that language and update the `switch` to make it available. With the current approach, new languages can be added by just adding a new file.
2. The performance increase could also be achieved, by reading all the text files once on application startup and storing them in memory.

Just my two cents :)

**Comment by safestak-keith** [comment]
Hey @eddex, great to see another face here and appreciate your input! We had a bit of a discussion earlier in #12 and ended up going for this explicit / strongly typed option which explains this exact implementation in the PR. 

As you might imagine plenty of tradeoffs were considered, ultimately IO removal, fewer moving parts and less error-prone code made up the big bulk of the reason. The explicit mapping of the WordLists enum to the static types in the switch also allowed a neat form of compile-time verification too, since new languages could potentially be added to the enum without a txt file available as an embedded resource.

**Review by nothingalike — APPROVED** [review]

**Comment by nothingalike** [comment]
@safestak-keith we just need to update the Version for the nuget deployment

**Comment by nothingalike** [comment]
@safestak-keith does this have any breaking changes? seems this is just updating how to handle mnemonics but not affecting how you use the library, is that correct?

**Comment by safestak-keith** [comment]
> @safestak-keith does this have any breaking changes? seems this is just updating how to handle mnemonics but not affecting how you use the library, is that correct?

Correct, no API/contract changes to the consumer.

> @safestak-keith we just need to update the Version for the nuget deployment

Is there anything I need to do apart from the simple patch bump in the CardanoSharp.Wallet.csproj `Version` to make it `2.0.1`? 

On that note, I can help implement a GitHub Action which does automatic semantic version increments with the usual build, test and publish package workflow like [what cscli has here](https://github.com/CardanoSharp/cscli/blob/main/.github/workflows/build.yaml), bounty is at your discretion!

**Comment by nothingalike** [comment]
> Is there anything I need to do apart from the simple patch bump in the CardanoSharp.Wallet.csproj Version to make it 2.0.1?

Yeah 2.0.1 is perfect. I can coordinate both PR merges though!

**Pull request merged**
