### PR TITLE
Adding Plutus and Smart Contract Support to CardanoSharp

### PR DESCRIPTION
**Pull request by NicholasMaselli**
Finally

### CODE REVIEW

**Review by nothingalike — APPROVED** [review]
LGTM!

**Comment by nothingalike** [comment]
@NicholasMaselli Please post a mainnet cardano address in the comments here for bounty rewards if you agree with the below terms

Nick: 2000 ADA for Development

**Comment by NicholasMaselli** [comment]
> @NicholasMaselli Please post a mainnet cardano address in the comments here for bounty rewards if you agree with the below terms
> 
> Nick: 2000 ADA for Development

Awesome! Here is the address: addr1q80ukhmvgtm498e3h6pwpe52whpdh98yy4qfwup5zqg7lqz75jq4yvpskgayj55xegdp30g5rfynax66r8vgn9fldndskl33sd

**Comment by cmorgado** [comment]
No update on documentation in order to learn how to use this new features?

**Comment by NicholasMaselli** [comment]
> No update on documentation in order to learn how to use this new features?

@nothingalike is adding this tonight / tomorrow

**Comment by nothingalike** [comment]
Transaction Bounty Payment [05dd7cd4df0f18fee676b9b6a5d42090bef9363d246e39d7122f7ae5703435d7](https://cardanoscan.io/transaction/05dd7cd4df0f18fee676b9b6a5d42090bef9363d246e39d7122f7ae5703435d7)

**Pull request merged**
